"""The slide editor: one record, as the slide it contributes to its cycle's deck.

A deck is generated, and a generated deck is the floor somebody edits up from
rather than the ceiling — `deck.py` has said so since it was written, and until
now there was no way to do the editing. This is that way: three panes on the
record's own page, at `/detail/<id>?view=slide`.

**On the record's page and not on a page of its own.** jcanton, 2026-08-25:
"don't make it /slide/<id> but keep it in /detail/<id> if possible". It is a
query on the same path, so the address is the record's, a link to it is a link
to the record, and the back button behaves. It is a separate RENDERER because
`detail.py` is three thousand lines of one page's machinery — a co-editing
socket, a draft store, four view states and two editors — and none of it is what
a slide editor needs. A fourth state threaded through `showView` would have
inherited all of it to use none of it.

**Three panes, not four.** The record as it reads on the left — facts above the
document, the arrangement the record page already draws — the choosing in the
middle, the slide as it will look on the right. There is no frontmatter editor
in the middle pane because a slide's frontmatter is DERIVED: the title, the
chips, the appetite, the owner and the id all come off the record, they are on
the left already, and a box to retype them into would be the second copy of one
fact this whole tool exists to end.

**One save model, and it is the record's.** Save writes `slide:` through
`PATCH /api/record/<id>`, the same door the record page uses, so a slide edit
gets the same compare-and-swap, the same three-way merge and the same conflict
report as everything else. The body editor is not on screen in this mode, so the
page still has exactly one thing Save means.
"""

from __future__ import annotations

from collections.abc import Callable

from markupsafe import Markup

from ..index import Index
from ..model import Record, lead_text
from ..vendor import _ace
from .controls import _combobox_html
from .deck import _DECK_STYLE, _deck_view, _said, _seeded, choosable, slide_html
from .detail import _body_html, _fact_rows, _progress_view, _slidebar
from .editor import _ACE_SURFACE, _ace_wanted
from .env import _fragment
from .markdown import _inlined_assets
from .shell import ROUTES, Links, _page
from .styles import _DETAIL_STYLE
from .tokens import _human


def _boxes(record: Record) -> list[dict]:
    """The section checkboxes, reconciled with the record as it is right now.

    **The reconciliation is here and it writes nothing.** jcanton asked for a
    "bottommatter which is autogenerated when opening the slide editing page",
    and this is that, minus the write: a GET that commits would fire on every
    visit, including every visit by somebody the write path would refuse, so
    opening the page would be a 403 for a reader and a commit for everybody
    else. Computing it on open and storing it on Save is the same outcome with
    neither.

    A section the record has grown since the slide was last saved is offered
    unticked — jcanton, 2026-08-25: "newly-discovered section should always
    arrive but not checked, default is leave out". A record that has never been
    personalised is seeded from `_seeded` instead, so its boxes describe the
    slide the deck is drawing for it today and pressing Save without touching
    anything changes nothing. Without that carve-out the first Save on every
    record in the plan would have blanked its slide.

    A name stored by a section that has since been DELETED is not offered, and
    is not lost either: it stays in the file, `only_sections` matches nothing for
    it, and it starts drawing again if the heading comes back. Dropping it here
    would turn a rename-and-rename-back into a silent deletion.
    """
    stored = record.slide if record.slide is not None else _seeded(record)
    chosen = set(stored.sections)
    fresh = record.slide is None
    return [
        {
            "name": name,
            "label": _human(name),
            "on": name in chosen,
            # What the box would have been, so the editor can mark what has
            # arrived since the last save. A person who opens a slide they
            # personalised in July wants to see WHICH heading is new, not to
            # diff two lists in their head.
            "new": not fresh and name not in chosen,
            "bet": is_bet,
        }
        for name, is_bet in choosable(record)
    ]


def _place(index: Index, record: Record) -> int | None:
    """Which slide of its cycle's deck this record's first slide is, counting the
    title slide as one.

    Asked of `_deck_view` itself rather than counted here, so the number on this
    page and the number under the presenter's thumb are the same number. A second
    count would agree with the deck until the day somebody changed the ordering
    or the leaf rule, and then it would be a page confidently naming the wrong
    slide — which is worse than naming none.
    """
    if record.cycle is None:
        return None
    drawn = _deck_view(index, record.cycle, ROUTES)["slides"]
    for at, one in enumerate(drawn):
        if one["id"] == record.id:
            # Plus two: `enumerate` is zero-based and the title slide is drawn
            # by the template rather than by `slides`, so it is in neither.
            return at + 2
    return None


_SLIDE = """
{#- Where you came FROM, and not where this slide happens to live. It hardcoded
    "← deck N", which is right when you arrived from the deck and a lie when you
    arrived from Table or from Records — jcanton, 2026-08-25. `class="origin"` is
    the hook the shell's own back-link script already looks for: a page rendered
    without an origin name of its own reads the stamp this tab left on the way in
    and rewrites both the address and the label. One mechanism for one question,
    and this page had invented a second. -#}
<p class="back"><a class="origin" href="{{ links.records }}">← all records</a></p>

<article class="record slideedit" data-id="{{ e.id }}">
  {#- The same row of controls the record page carries, because this IS a view of
      that record and jcanton was explicit that the bar must not vanish when you
      reach it: "the top editor bar with the icons for the four views and similar
      have disappeared. that should not happen".

      The three segments are LINKS here rather than the buttons they are on the
      record page. There they toggle a class on an article already on screen;
      here the document they lead to is a different page, so the thing that gets
      you there is a link — `_VIEW_SEGMENTS`' buttons would have been three
      controls that do nothing at all.

      `?edit` and `?both` are FLAGS and not values, because that is what the
      record page reads: `VIEW_ASKED.has(name)`, off an address the observed
      HackMD note spells `?both=`. Preview is the bare address, since it is the
      page's own landing state. Written the way the reader already parses it
      rather than in a second spelling this page would have had to teach it.

      **No Delete here.** The row on the record page carries one and this one
      does not, which is a difference worth stating: deleting is a flow — a
      confirmation row, a second press, a redirect — that lives in `detail.py`
      with the record it is about, and a button here would either be dead or be
      that whole flow copied. A control whose only answer is a refusal is a dead
      end somebody can only find by pressing it, which is the argument that
      already kept a Delete off the create form. -#}
  {% if editable %}
  {#- No drawings button here either: it is a `FORMATS` entry drawn into
      `#marks` below, beside the image button. See `detail.py`'s copy of this
      bar. -#}
  <p class="editbar">{{ slidebar }}
    <span id="views" class="views" role="group" aria-label="How the document is shown">
      <a class="seg" href="{{ links.record }}{{ e.id }}?edit" aria-pressed="false"
         aria-label="Write" title="Write">
        <svg viewBox="0 0 24 24" aria-hidden="true">
        <path d="M4 20h4L19.2 8.8a2.55 2.55 0 0 0-3.6-3.6L4.4 16.4 4 20Z"/></svg></a>
      <a class="seg" href="{{ links.record }}{{ e.id }}?both" aria-pressed="false"
         aria-label="Write and preview" title="Write and preview">
        <svg viewBox="0 0 24 24" aria-hidden="true">
        <rect x="3" y="5" width="18" height="14" rx="1.6"/><path d="M12 5v14"/></svg></a>
      <a class="seg" href="{{ links.record }}{{ e.id }}" aria-pressed="false"
         aria-label="Preview" title="Preview">
        <svg viewBox="0 0 24 24" aria-hidden="true">
        <path d="M2.5 12S6 6.2 12 6.2 21.5 12 21.5 12 18 17.8 12 17.8 2.5 12 2.5 12Z"/>
        <circle cx="12" cy="12" r="2.7"/></svg></a>
    </span>
  </p>
  {% endif %}
  <h1>{{ e.title }}</h1>
  {#- Whether this slide will actually be DRAWN, said before anybody spends ten
      minutes on it. `_deck_view` takes leaves only and takes them from one
      cycle, so there are two ordinary ways to be looking at a slide that no deck
      contains — and neither of them is a fault, so neither is an error. The
      editor works in both: what is refused is letting somebody find out
      afterwards. -#}
  <p class="meta"><code>{{ e.id }}</code> ·
    {% if not e.cycle %}<span class="hint">this record is not bet into a cycle,
      so it is on no deck yet — the slide is here and will be drawn the moment it
      is</span>
    {% elif e.rollup %}<span class="hint">this record's tasks each get their own
      slide, so it has none of its own — a rollup on a deck would put the same
      work on the screen twice. The slide below is what it would draw if its
      tasks went away.</span>
    {% elif e.at and links.deck %}<a href="{{ links.deck }}{{ e.cycle }}">slide {{ e.at }} of the
      cycle {{ e.cycle }} deck</a>
    {% elif links.deck %}<a href="{{ links.deck }}{{ e.cycle }}">on the cycle
      {{ e.cycle }} deck</a>
    {#- `links.deck` is empty in the static export, where a deck is of one cycle
        and the export writes one file per view of the whole plan — so there is
        no file to point at. The cycle page has the same guard for the same
        reason: no link, rather than a link to something nobody wrote. -#}
    {% else %}<span class="hint">on the cycle {{ e.cycle }} deck</span>{% endif %}</p>

  {% if editable %}
  {#- Save and Reset, in the bar the other editors put them in and with the same
      two words. Reset undoes and stays — it does not leave the editor — which is
      the decision `_editbar` records on the record page; a second spelling of
      one control is how `in_progress` became three different words. -#}
  <p class="editbar" id="editbar">
    <button type="button" id="save" class="primary">Save</button>
    <button type="button" id="reset">Reset</button>
    <span class="hint" id="state" role="status" aria-live="polite"></span>
  </p>
  <input type="hidden" id="base" value="{{ base_commit }}">
  {% endif %}

  {#- **No Hide button.** There was one, and it is gone because the drag now does
      the whole job — jcanton, 2026-08-25: "would it be possible to hide the
      record dynamically ... we can get rid of the hide/show button in that
      case."

      The objection the button answered was real and is answered differently: a
      pane dragged to nothing leaves a handle nobody can find again. Here the
      handle does not go anywhere. It stays against the left edge at zero width,
      it keeps its hit area and its focus ring, and dragging it right past the
      same threshold brings the record back. -#}
  <div class="panes3" id="panes3" data-fills>
    {#- LEFT: the record as it reads. The same facts list and the same document
        the record page draws, from the same three functions, because a second
        rendering of a record is a second thing to keep in step — and this is
        the pane somebody is reading FROM while they decide what goes on the
        slide, so it has to be what the record actually says. -#}
    <section class="pane read" id="pane-read" aria-label="The record">
      <dl class="facts">
        {% for row in e.rows %}
        <dt class="{% if row.derived %}derived{% endif %}">{{ row.label }}</dt>
        <dd class="{% if row.derived %}derived{% endif %}">{{ row.display }}</dd>
        {% endfor %}
      </dl>
      {#- A pitch's rollup, where there is one. `tasks` and never `items`: a
          Jinja lookup finds `dict.items` first and the template raises
          `'builtin_function_or_method' object is not iterable` — which
          `_progress_view` has a comment about, written the last time somebody
          did this, and which this template did anyway. -#}
      {% if e.progress %}
      <section class="progress">
        <h2>Progress <span class="tally">{{ e.progress.text }}</span></h2>
        <ul>{% for task in e.progress.tasks %}
          <li class="{{ 'ticked' if task.done else '' }}"><span class="chip
            {{ task.status_class }}">{{ task.status|human }}</span> {{ task.title }}</li>
          {% endfor %}</ul>
      </section>
      {% endif %}
      <div class="doc read">{{ e.body }}</div>
    </section>

    {#- The two joins, and the same control the record page's split view uses:
        `role="separator"`, focusable, and answering an arrow key as well as a
        pointer. A splitter that answers only a mouse is the same defect as a
        table that answers only a double-click, which this repository has already
        shipped once. -#}
    <div class="pgrip" role="separator" tabindex="0" aria-orientation="vertical"
         aria-label="Resize the record pane" data-at="0"></div>

    {#- CENTRE: what goes on the slide. -#}
    <section class="pane pick" aria-label="What goes on the slide">
      <p class="choice drop">
        <label><input type="checkbox" id="skip" {% if e.slide.skip %}checked{% endif %}>
          Leave this slide out of the deck</label>
        <span class="hint">It stays on the rail, greyed, so you can put it back.</span>
      </p>

      {#- The two the deck already lifted, above the line, because that is where
          they are drawn on the slide itself: the ticked points and the pull
          requests sit above the rule the document starts under. -#}
      <fieldset class="choice">
        <legend>Above the line</legend>
        <label><input type="checkbox" class="opt" data-key="progress"
          {% if e.slide.progress %}checked{% endif %}> Include progress</label>
        <label><input type="checkbox" class="opt" data-key="prs"
          {% if e.slide.prs %}checked{% endif %}> Include PRs</label>
      </fieldset>

      <fieldset class="choice">
        <legend>From the record's body</legend>
        {% if e.lead_exists %}
        <label><input type="checkbox" class="opt" data-key="lead"
          {% if e.slide.lead %}checked{% endif %}> Opening text</label>
        {% endif %}
        {% for box in e.boxes %}
        <label class="{% if box.new %}fresh{% endif %}">
          <input type="checkbox" class="sec" value="{{ box.name }}"
            {% if box.on %}checked{% endif %}> {{ box.label }}
          {% if box.bet %}<span class="tag">the bet</span>{% endif %}
          {% if box.new %}<span class="tag new">new</span>{% endif %}
        </label>
        {% endfor %}
        {% if not e.boxes and not e.lead_exists %}
        <p class="hint">This record's document has nothing in it yet. Whatever you
           write below is the whole slide.</p>
        {% endif %}
      </fieldset>

      <p class="field">
        <label for="prose">And on the slide, in your own words</label>
        <span class="hint">Markdown. A line reading <code>\\newslide</code> starts
          another slide for this record — the second is titled
          “{{ e.title }} (2)”. Paste or drop a picture to put it in the plan.</span>
      </p>
      {#- The same three strips the record page puts around its box, in the same
          order and with the same ids, because they are filled by the same
          functions: `applyMark` writes the toolbar into `#marks`, `attachUploads`
          reports into `#upload`, `attachGutter` into `#gutter-note` and
          `attachStatus` wraps `#statusbar`. jcanton, 2026-08-25: "editor in the
          slide body editing: it doesn't have the bottom bar with draft/spaces/
          keymap etc, can you include it please?"

          Reached by inlining `controls.py`'s whole editor block rather than by
          re-deriving any of it here — that block is what declares `EDITOR`,
          `INDENT` and `KEYMAPS`, which is also why this page's Ace surface had
          to default them. Two copies of a status bar is two things to keep in
          step, and the one nobody would notice going stale is the small one.

          No `#draftevery`: a draft is the record page's, where a body is being
          co-edited and losing it means losing writing git never saw. This box
          saves through the same Save as the checkboxes above it. -#}
      <p class="field bodybar markbar">
        <span id="marks" class="marks"></span>
        <span class="hint" id="upload" role="status" aria-live="polite"></span>
        <span class="hint" id="gutter-note" role="status" aria-live="polite"></span>
      </p>
      <div class="bodywrap">
        <textarea id="prose" name="prose" class="field body-field"
          aria-label="What this slide says in your own words">{{ e.slide.body }}</textarea>
      </div>
      <p class="field bodybar statusbar" id="statusbar"></p>
    </section>

    <div class="pgrip" role="separator" tabindex="0" aria-orientation="vertical"
         aria-label="Resize the slide pane" data-at="1"></div>

    {#- RIGHT: the slide, built by the same function the deck builds it with, so
        this pane and the projector cannot disagree. -#}
    <section class="pane show" aria-label="The slide">
      <div class="sized" id="preview">{{ e.preview }}</div>
      <p class="hint" id="fitnote" role="status" aria-live="polite"></p>
    </section>
  </div>
</article>
"""


_SLIDE_STYLE = """
/* Three columns that each scroll on their own, because they are three different
   documents about one thing and a reader moves down one of them at a time. The
   middle is the widest because it is the only one being typed into; the right is
   sized to the slide's own 16:9 rather than to a share of the row, so the
   preview is never a shape the projector is not. */
/* Three panes and two handles, as five grid tracks. The widths are custom
   properties so the drag writes ONE number per column and the grid does the
   arithmetic — a `grid-template-columns` rebuilt in JavaScript is a second place
   the layout is decided, and it is the copy that gets it wrong at a narrow
   window.

   `minmax(0, …)` on every column, not a bare fraction: a grid track's automatic
   minimum is its content, so a pane holding a wide code block or a 1280px slide
   refuses to shrink below it and the drag simply stops working part-way. This is
   the same `min-width: 0` note the record page's `.panes` carries, in the shape
   a grid needs. */
.panes3 {
  display: grid; gap: 0;
  grid-template-columns:
    minmax(0, var(--pane-read, 1fr)) .75rem
    minmax(0, var(--pane-pick, 1.15fr)) .75rem
    minmax(0, var(--pane-show, 1fr));
  align-items: start;
}
/* Folded: the record pane and the handle beside it stop taking a track at all.
   `0` and not `display: none` on the pane, so the pane keeps its scroll position
   and its rendered document — unfolding is instant and does not re-render a
   whole record. */
/* **Folding is a WIDTH, not a second template.** `--pane-read: 0px` and the
   first track is gone; nothing else about the row changes.

   It was a `grid-template-columns` of its own, and that was the bug jcanton
   found: the folded template named `1.15fr` and `1fr` while the drag went on
   writing `--pane-pick` and `--pane-show` in pixels, so the two remaining panes
   sat at a fixed ratio and the handle between them did nothing at all. Two
   templates is two places the layout is decided, and the second one silently
   ignored the first's numbers.

   The handle beside the folded pane STAYS, and that is the whole of the
   dynamic-fold gesture: at zero width it sits against the left edge, and
   dragging it right is what brings the record back. A control that vanished with
   the thing it controls would leave nothing to drag. */
.panes3.folded > .pane.read {
  visibility: hidden; padding: 0; border: 0; overflow: hidden;
}

/* The handle between two panes. Its whole visible self is a hairline that
   thickens under the pointer — the same device and the same `--accent` as the
   record page's `#splitter`, because two spellings of "drag this" on one app is
   one too many. */
.pgrip {
  align-self: stretch; cursor: col-resize; position: relative;
  background: none; border: 0;
}
.pgrip::before {
  content: ""; position: absolute; inset: 0 calc(50% - 1px);
  background: var(--line); border-radius: 1px;
}
.pgrip:hover::before, .pgrip:focus-visible::before, .pgrip.dragging::before {
  background: var(--accent); inset: 0 calc(50% - 1.5px);
}
.panebar { margin: 0 0 .5rem; }
.panebar button {
  font: inherit; font-size: 12px; color: var(--muted);
  background: none; border: 1px solid var(--line); border-radius: 3px;
  padding: .2rem .5rem; cursor: pointer;
}
.panebar button:hover { color: var(--accent); }
/* The row is as tall as the window has left, measured by the shell's `--room`
   rather than by a `100vh` minus a hand-counted stack — this said
   `calc(100vh - 12rem)`, which knew nothing about the bar above it, the heading,
   or the footer and its margins below. `data-fills` on the grid is how a page
   tells the shell which box that is. */
.panes3 { height: var(--room); }
.panes3 > .pane {
  min-width: 0; max-height: 100%; overflow: auto;
  border: 1px solid var(--line); border-radius: 4px; padding: .9rem 1rem;
  background: var(--surface);
}
/* One column under a narrow window, in reading order: what the record says,
   then what you are choosing, then what it looks like. `1100px` is where the
   middle column stops holding a checkbox label and its two tags on one line. */
/* One column under a narrow window, in reading order, and the handles go with
   it: a col-resize grip on a stacked layout resizes nothing. */
@media (max-width: 1100px) {
  .panes3, .panes3.folded { grid-template-columns: minmax(0, 1fr); }
  .panes3 > .pgrip { display: none; }
}

.panes3 .facts { margin: 0 0 1rem; }
.panes3 .read .doc { border-top: 1px solid var(--line); padding-top: .8rem; }

.choice { border: 0; margin: 0 0 1rem; padding: 0; }
.choice legend {
  font-size: 11px; font-weight: 600; letter-spacing: .06em;
  text-transform: uppercase; color: var(--muted); padding: 0;
}
.choice label { display: flex; align-items: baseline; gap: .45rem; margin: .3rem 0; }
/* The one control on this page that takes something away, so it is separated
   from the ones that add. */
.choice.drop { border-bottom: 1px solid var(--line); padding-bottom: .8rem; }
.choice .tag {
  font-size: 10px; letter-spacing: .04em; text-transform: uppercase;
  color: var(--muted); border: 1px solid var(--line); border-radius: 3px;
  padding: 0 .3rem;
}
/* What has arrived since this slide was last saved. Marked rather than ticked:
   the rule is that a new section stays out until somebody says otherwise, and a
   mark is how they find out there is something to say. */
.choice .tag.new { color: var(--warn); border-color: var(--warn); }

/* **The prose box is visible here without an editing session**, and it needs a
   rule because this article wears `record`. That class is what gives the page
   `--writing` and the editbar its styling, and it brings `styles.py`'s
   `.field { display: none }` with it — the record form's fields are hidden until
   `.record.editing` turns them on, which is right for a page whose facts column
   swaps values for controls and wrong for this one, where the box IS the page.
   Measured in Chrome: the prose box and the Ace surface mounted into it both
   computed `display: none` and laid out 0x0, so the middle pane simply ended
   after the checkboxes.

   `:not([hidden])` keeps the attribute working, and that is not decoration: Ace
   hides the original `<textarea>` with `hidden` when it mounts, and a rule that
   overrode it would draw the plain box underneath the editor that replaced it.
   (0,3,0) against the bare `.field`'s (0,1,0), so it wins on weight rather than
   on which stylesheet happens to be inlined second. */
.slideedit .field:not([hidden]) { display: block; }

/* The preview is the deck's own slide at the width of this column. `.sized` is
   the deck stylesheet's fixed-canvas switch, so this pane gets the same 1280x720
   geometry, the same clip and the same `.spills` mark as the projector — which
   is the entire point of the pane. */
#preview { --fit: .32; }
#preview .slide { margin: 0 auto; }
"""


_SLIDE_SCRIPT = """
<script>
(() => {
const ID = {{ e.id|tojson }};
const MAY_WRITE = {{ editable|tojson }};
const ARTICLE = document.querySelector('.slideedit');
const PROSE = document.getElementById('prose');
const PREVIEW = document.getElementById('preview');
const FITNOTE = document.getElementById('fitnote');
const SAVE = document.getElementById('save');
const RESET = document.getElementById('reset');
const STATE = document.getElementById('state');
const BASE = document.getElementById('base');
// The document as it was when this page was rendered, and the ONE thing Reset
// restores from. Never `defaultValue`: a browser restoring a form on a back
// navigation writes the box and leaves `defaultValue` alone, so Reset would
// have put back something the reader never saw. Same decision, same reason, as
// the record editor's `BASELINE`.
// Ace, where the page was given it. The plain box stays in the DOM and stays
// the thing `state()` falls back to, exactly as it does on the record page —
// one place knows a textarea has a `.value`, and it is not this file.
//
// **Before `BASELINE`, and that ordering is the whole of a defect this shipped
// with.** `BASELINE` calls `state()`, which read `typeof text === 'function'`
// while `text` was still in its temporal dead zone — and `typeof` on a `const`
// in TDZ THROWS rather than answering "undefined". The ReferenceError landed on
// the first executable line of the block, so nothing after it ever ran: no
// checkbox listener, no Save, no Reset, no preview. `AGENTS.md` names this exact
// tell — "`typeof x` throwing TDZ on a `let` is the tell: execution never
// reached that line" — and it was written about the last time this happened.
//
// The `typeof` guard is gone with it. It was papering over the ordering rather
// than defending against anything: `text` is declared right here, and a guard
// that can only be false while the code is broken is a guard that hides the
// break.
// `bodySurface`, not `aceSurface` called directly: the record page's `SURFACE`
// is built through `bodySurface` and this one used to call `aceSurface` on its
// own, so on `?editor=plain` — with no Ace on the page and `window.aceSurface`
// undefined — `SURFACE` was `null` regardless of `MAY_WRITE`, and every
// `attach*` call below it (including `attachDrawing`) never ran at all. See
// the comment over that block.
const SURFACE = MAY_WRITE ? bodySurface(PROSE) : null;
const text = () => SURFACE ? SURFACE.text() : PROSE.value;

function state() {
  const on = key => {
    const box = ARTICLE.querySelector(`.opt[data-key="${key}"]`);
    return box ? box.checked : true;
  };
  return {
    skip: document.getElementById('skip').checked,
    progress: on('progress'),
    prs: on('prs'),
    lead: on('lead'),
    sections: [...ARTICLE.querySelectorAll('.sec')]
      .filter(box => box.checked).map(box => box.value),
    body: text(),
  };
}

// Taken AFTER `text` exists, for the reason written above it. Never
// `PROSE.defaultValue`: a browser restoring a form on a back navigation writes
// the box and leaves `defaultValue` alone, so Reset would put back something the
// reader never saw — the decision `BASELINE` on the record page records.
const BASELINE = JSON.stringify(state());

function dirty() { return JSON.stringify(state()) !== BASELINE; }

function said(words) { if (STATE) STATE.textContent = words; }

// --- The preview --------------------------------------------------------
// Asked of the SERVER, and that is the decision worth the round trip. A slide
// is markdown through `_markdown`, sections chosen by `only_sections`, a
// checklist lifted by `checklist_items` and pull requests linked by `_pr_link` —
// five functions in Python, none of which exists in this page. A preview drawn
// here would be a sixth rendering of a slide, written in a second language,
// agreeing with the projector only for as long as somebody kept it in step. The
// deck's whole argument is against exactly that.
let asked = null;
let waiting = false;
const PREVIEW_MS = 400;

async function draw() {
  waiting = false;
  const sending = JSON.stringify(state());
  const answer = await fetch('/api/slide/preview', {
    method: 'POST',
    headers: {'content-type': 'application/json'},
    body: JSON.stringify({record_id: ID, slide: state()}),
  });
  if (!answer.ok) {
    // The preview failing is not the save failing, and it must not read as
    // though it were: the text in the box is untouched and still saveable.
    FITNOTE.textContent = 'The preview could not be drawn just now.';
    return;
  }
  const drawn = await answer.json();
  PREVIEW.innerHTML = drawn.html;
  fit();
}

function refresh() {
  if (waiting) clearTimeout(asked);
  waiting = true;
  asked = setTimeout(draw, PREVIEW_MS);
}

// Does it fit? Asked of the browser, after the drawing, because whether 300
// words fit in 720px depends on the font and the wrapping and only the thing
// doing the layout knows both. This is the pane's real job: the canvas is fixed
// and clipped, so without this mark an author would be told nothing at all
// about the paragraph the room is never going to see.
function fit() {
  const room = PREVIEW.clientWidth;
  if (room > 0) PREVIEW.style.setProperty('--fit', String(room / 1280));
  const over = [...PREVIEW.querySelectorAll('.slide')]
    .filter(slide => slide.scrollHeight > slide.clientHeight + 1);
  for (const slide of PREVIEW.querySelectorAll('.slide'))
    slide.classList.toggle('spills', over.includes(slide));
  FITNOTE.textContent = over.length
    ? `${over.length} of these slides ${over.length === 1 ? 'holds' : 'hold'} more than fits. `
      + 'Take something out, or split it with \\\\newslide.'
    : '';
}

// --- Saving -------------------------------------------------------------
async function save() {
  if (!MAY_WRITE) return;
  SAVE.disabled = true;
  said('Saving…');
  try {
    const answer = await fetch('/api/record/' + encodeURIComponent(ID), {
      method: 'PATCH',
      headers: {'content-type': 'application/json'},
      // `body: null` and not the record's body: this editor does not have the
      // record's document on screen and must not write one. A save that carried
      // an empty body would erase the shaping document from a page that never
      // showed it.
      body: JSON.stringify({base_commit: BASE.value, fields: {slide: state()}, body: null}),
    });
    const result = await answer.json().catch(() => ({}));
    if (!answer.ok) {
      // The shell's `refusal`, which is the only reading that knows a 409 has
      // two shapes. `result.detail` alone was backwards: this route is
      // `PATCH /api/record`, whose real concurrent write answers through
      // `_result` with a `conflict` report and NO `detail` at all — so the one
      // case this line exists for was the one case it could not say, and
      // "That could not be saved." stood over the report naming the file and
      // every field that disagreed.
      said(refusal(result, answer.status));
      return;
    }
    if (result.commit) BASE.value = result.commit;
    said('Saved.');
  } catch (error) {
    // The connection went while the request was in the air. This was `try` and
    // `finally` with no `catch`: the rejection escaped as an unhandled one and
    // the bar was left reading "Saving…" for ever — a sentence that says the
    // thing is still happening, about a thing that stopped.
    //
    // It does not claim what reached the server. A fetch rejects when the
    // answer is lost as readily as when the request never left, so this says
    // what to do instead — and pressing Save again is safe either way.
    //
    // Safe because it is the SAME write, and not because the store would refuse
    // it. `_merge_frontmatter` skips every key whose stored value already equals
    // the one being sent, so a save that did land, re-sent unchanged against the
    // same `BASE.value`, merges with itself and answers 200. Predicting a
    // refusal here would be predicting something the store does not do.
    said(`Not saved — ${error.message}. Press Save again: it sends the same edit `
         + 'against the same base, so a first save that did land is not written twice.');
  } finally {
    SAVE.disabled = false;
  }
}

if (MAY_WRITE) {
  SAVE.addEventListener('click', save);
  RESET.addEventListener('click', () => {
    const was = JSON.parse(BASELINE);
    document.getElementById('skip').checked = was.skip;
    for (const box of ARTICLE.querySelectorAll('.opt'))
      box.checked = was[box.dataset.key];
    for (const box of ARTICLE.querySelectorAll('.sec'))
      box.checked = was.sections.includes(box.value);
    // `splice` and never `setValue`: it is the surface's only write, and
    // `test_the_second_surface_never_sets_or_replaces_the_whole_document` holds
    // it to that by reading the shipped page. Whole-document boundaries, so the
    // UTF-16 index space `positionToIndex` uses cannot cut a surrogate pair —
    // the defect that shipped once already and rewrote somebody's emoji.
    if (SURFACE) SURFACE.splice(0, text().length, was.body);
    else PROSE.value = was.body;
    said('Reset.');
    refresh();
  });
  // Nothing autosaves here, so leaving with unsaved work has to be said. One
  // model per page and it is visible: the bar carries the state and this is the
  // last thing it can say.
  addEventListener('beforeunload', event => {
    if (dirty()) event.preventDefault();
  });
}

// --- Three panes, two handles, one fold --------------------------------------
//
// The widths are written as custom properties and the grid does the arithmetic;
// see the stylesheet for why a rebuilt `grid-template-columns` would be a second
// place the layout is decided.
//
// Remembered, because a reader who has made room for the preview means it for
// the next slide too — through the shell's `remembered` door, which is the one
// place that knows `localStorage` throws on the property itself in a private
// window.
const PANES = document.getElementById('panes3');
const PANE_KEY = 'openproj:slidepanes';
const PANE_VARS = ['--pane-read', '--pane-pick', '--pane-show'];
// The narrowest a pane may be dragged before it stops being a pane. Below this
// the record FOLDS rather than becoming a sliver — a 40px column of clipped
// words is not a reading pane, it is a rendering artefact, and the gesture that
// produced it was somebody asking for the room.
//
// One number for both directions, so folding and unfolding happen at the same
// place and the handle does not stick: drag left through it and the record goes,
// drag right through it and the record comes back at exactly this width.
const PANE_FOLD = 120;

function paneWidths() {
  return [...PANES.querySelectorAll(':scope > .pane')]
    .map(pane => pane.getBoundingClientRect().width);
}

// Every width written down at once, in pixels. Pinning all three is what stops
// the row re-flowing when one `fr` is turned into a length beside two others —
// a grid with two fixed tracks and one flexible one gives the flexible one
// everything left over, which is not what a drag between two neighbours means.
function paneSet(widths) {
  widths.forEach((width, at) =>
    PANES.style.setProperty(PANE_VARS[at], Math.max(0, Math.round(width)) + 'px'));
  PANES.classList.toggle('folded', widths[0] < 1);
  fit();
}

function panesRemember() {
  remembered.set(PANE_KEY, JSON.stringify({
    widths: PANE_VARS.map(name => PANES.style.getPropertyValue(name)),
  }));
}

(() => {
  const held = remembered.map(PANE_KEY);
  if (!Array.isArray(held.widths) || held.widths.length !== PANE_VARS.length) return;
  // Only strings that look like a length. A stored value is a value somebody's
  // devtools can write and it reaches `grid-template-columns`, so this is an
  // allowlist rather than a trust — the same shape as every other stored value
  // this app reads back.
  const clean = held.widths.map(value =>
    typeof value === 'string' && /^[0-9]+(\\.[0-9]+)?px$/.test(value) ? parseFloat(value) : null);
  if (clean.every(width => width !== null)) paneSet(clean);
})();

// One handle moves the two panes it sits between and nothing else, so the row
// keeps its total width and the pane on the far side does not move.
//
// **The fold happens here rather than in a mode**, which is what makes it
// reversible with the same gesture: a read pane dragged under `PANE_FOLD`
// collapses to nothing and gives its width to its neighbour, and the same handle
// dragged back out past the threshold restores it. Nothing latches, so there is
// no state to get stuck in.
function slide(at, byPixels) {
  const was = paneWidths();
  const total = was[at] + was[at + 1];
  let left = was[at] + byPixels;
  if (at === 0 && left < PANE_FOLD) {
    // Folded, or on the way back. Below half the threshold it is shut; above it
    // the record reappears at the threshold rather than at one pixel, so the
    // drag never leaves a pane too narrow to read.
    left = left < PANE_FOLD / 2 ? 0 : PANE_FOLD;
  } else {
    left = Math.max(PANE_FOLD, Math.min(total - PANE_FOLD, left));
  }
  const next = was.slice();
  next[at] = left;
  next[at + 1] = total - left;
  paneSet(next);
}

for (const grip of PANES.querySelectorAll(':scope > .pgrip')) {
  const at = Number(grip.dataset.at);
  grip.onpointerdown = event => {
    grip.setPointerCapture(event.pointerId);
    grip.classList.add('dragging');
    // Measured against where the POINTER started rather than accumulated frame
    // by frame. A running total drifts once a pane hits its floor: the pointer
    // keeps moving, the pane cannot, and the difference is silently thrown away
    // — so dragging back out lagged by however far past the edge you had gone.
    const from = event.clientX;
    const start = paneWidths();
    const move = e => {
      const was = paneWidths();
      // `slide` works in deltas, so the delta handed to it is measured from the
      // width this drag began at.
      slide(at, (e.clientX - from) - (was[at] - start[at]));
    };
    const stop = () => {
      grip.classList.remove('dragging');
      panesRemember();
      removeEventListener('pointermove', move);
      removeEventListener('pointerup', stop);
    };
    addEventListener('pointermove', move);
    addEventListener('pointerup', stop);
  };
  // The keyboard half. A separator that answers only a pointer is a control half
  // the readers of this page cannot use, and the quality floor asks for both.
  grip.onkeydown = event => {
    const step = event.key === 'ArrowLeft' ? -24 : event.key === 'ArrowRight' ? 24 : 0;
    if (!step) return;
    event.preventDefault();
    slide(at, step);
    panesRemember();
  };
  // Double-click puts the row back the way it starts — jcanton, 2026-08-25:
  // "have the double click mechanism on the bars to restore the default 1/3
  // spacing". The properties are REMOVED rather than set: the default lives in
  // the stylesheet, as the fallback in `var(--pane-read, 1fr)`, and writing the
  // numbers here would be that ratio in a second place.
  grip.ondblclick = () => {
    for (const name of PANE_VARS) PANES.style.removeProperty(name);
    PANES.classList.remove('folded');
    remembered.forget(PANE_KEY);
    fit();
    announce('Panes reset');
  };
}

// The toolbar, the upload path, the drawings menu, the gutter and the status
// strip — the same five calls the record page makes, in the same order, on
// the same surface. They come from `controls.py`'s block, which this page now
// inlines; guarded, because a reader gets no surface and none of them may be
// called on nothing.
//
// **The hole this used to inherit.** `SURFACE` above used to be built by
// calling `aceSurface(...)` directly rather than through `bodySurface`, so on
// `?editor=plain` with a writer at the keyboard, `SURFACE` was `null`, this
// whole block was skipped, and `#drawing` sat in the markup with nothing
// behind it — the same hole `attachUploads` and `attachEditing` were already
// sitting in. Fixed at the same time as `attachDrawing` was wired in here,
// rather than left for a new button to inherit: `render_slide_editor` had no
// test at all before this, and this block's own coverage is
// `test_the_plain_slide_editor_draws_a_toolbar_and_a_status_strip` and
// `test_a_reader_of_the_slide_editor_gets_no_surface_and_no_toolbar` in
// `tests/test_editor.py`.
if (SURFACE) {
  attachUploads(SURFACE, document.getElementById('upload'));
  // `false`: a slide is edited on a record that already exists, so there is
  // always something for a drawing to be embedded in.
  attachEditing(SURFACE, document.getElementById('marks'), false);
  // After `attachEditing`, which is what draws the button this wires, and into
  // `#state` rather than `#upload` — see the record page's own copy of this pair
  // for both.
  attachDrawing(SURFACE, document.getElementById('state'));
  attachGutter(SURFACE, document.getElementById('gutter-note'));
  attachStatus(SURFACE, document.getElementById('statusbar'));
}

ARTICLE.addEventListener('change', refresh);
if (SURFACE) SURFACE.onInput(refresh); else PROSE.addEventListener('input', refresh);
addEventListener('resize', fit);
// The preview is scaled against a pane the shell sizes, so it is re-scaled when
// that measurement moves.
addEventListener('openproj:room', fit);
document.fonts?.ready.then(fit);
fit();
})();
</script>
"""


def render_slide_editor(
    index: Index,
    record_id: str,
    links: Links = ROUTES,
    base_commit: str | None = None,
    may_write: bool = False,
    editor: str = "ace",
    asset: Callable[[str], bytes | None] | None = None,
) -> str:
    """One record's slide, as three panes on the record's own address.

    `base_commit` and `may_write` decide whether this is an editor or a reading
    of one, the same way they do on the record page and for the same reason: a
    reader offered a Save is offered a 403 dressed as a control, and the three
    panes are worth reading either way — the middle one simply becomes the list
    of what this slide is made of.
    """
    record = index.records[record_id]
    editable = bool(base_commit and may_write)
    slide = record.slide if record.slide is not None else _seeded(record)
    assets = _inlined_assets([record.body, slide.body], asset) if asset else {}
    view = {
        "id": record.id,
        "title": record.title,
        "cycle": record.cycle,
        # A pitch with tasks under it is a rollup and `_deck_view` gives it no
        # slide — its progress IS its tasks and its people are their people, so
        # a slide of its own would put the same work on the screen twice. Read
        # from the index rather than restated, so this and the deck cannot come
        # to different conclusions about what a leaf is.
        "rollup": bool(index.children.get(record.id)),
        # Which slide of the deck this is, so the line above is a place and not
        # only a link. `None` where the record is on no deck at all, which the
        # branch above has already taken.
        "at": _place(index, record),
        "rows": _fact_rows(index, record, links),
        "progress": _progress_view(index, record),
        "body": _body_html(record, links),
        "slide": slide,
        "boxes": _boxes(record),
        # Whether there is any opening text to offer a box for. A checkbox
        # governing something the record does not have is a control whose only
        # honest state is off, and a row of those is how a form stops being read.
        "lead_exists": bool(lead_text(_said(record))),
        "preview": slide_html(index, record, links, assets),
    }
    # `_fragment` and not `_compiled(...).render(...)`, which is what this was
    # and which silently escaped the whole page. `render` answers a `str`, so
    # `str + Markup` reaches `Markup.__radd__`, which escapes the left side: the
    # body arrived at `_page` as `&lt;article class=&#34;slideedit&#34;…`, a
    # complete and completely inert copy of the editor. `_fragment` types the
    # piece as the markup it is, which is the whole reason it exists — its own
    # docstring says so.
    ace = _ace_wanted(editor, base_commit, may_write)
    return _page(
        f"openproj — {record.title}: the slide",
        _fragment(
            _SLIDE,
            e=view,
            links=links,
            editable=editable,
            base_commit=base_commit or "",
            slidebar=_slidebar(record.id, links, here=True),
        )
        # **The library, then the surface, then this page's own script**, and
        # that order is load-bearing rather than tidy. These are classic scripts
        # and classic scripts run in document order, so a page script that asks
        # for `aceSurface` before `_ACE_SURFACE` has been parsed finds nothing —
        # measured: the box silently stayed a `<textarea>` and every Ace feature
        # was absent with no error anywhere, because the call is behind a
        # `window.aceSurface &&` guard that answered honestly.
        #
        # `_ace()` answers the BYTES of ace.js and not a script element, which is
        # the other half of the same defect: the record page wraps it
        # (`{% if ace %}<script>{{ ace }}</script>`) and this appended it bare,
        # so the whole library, licence comment first, rendered as visible text
        # at the foot of the page. `_ACE_SURFACE` brings its own `<style>` and
        # `<script>` and goes in as it is.
        + (Markup("<script>{}</script>").format(_ace()) if ace else Markup(""))
        + (_ACE_SURFACE if ace else Markup(""))
        # The editor's whole toolkit — the preferences (`EDITOR`, `INDENT`,
        # `KEYMAPS`), the mark toolbar, the uploader, the gutter and the status
        # strip. Inlined rather than picked apart: the five `attach*` calls this
        # page makes are the five the record page makes, and taking three
        # functions out of a block that declares thirty would be a second copy of
        # whichever three, going stale on the commit that changes the first.
        #
        # It also brings paste-and-drop image upload with it, which is what makes
        # `![figure](assets/…){width=60}` something somebody can produce here
        # rather than only type.
        + (_combobox_html(index) if editable else Markup(""))
        + _fragment(
            _SLIDE_SCRIPT,
            e=view,
            links=links,
            editable=editable,
        ),
        _DETAIL_STYLE + _DECK_STYLE + _SLIDE_STYLE,
        links,
        # `detail`, the same key the record page passes, and the choice matters
        # for more than the nav mark: `detail` is not a nav item, so `_page`
        # computes no origin, so this page READS the stamp instead of writing
        # one. It passed `records` and therefore stamped itself as "all records"
        # — which lit Records in the nav and, worse, overwrote the very stamp its
        # own back link was supposed to be reading.
        "detail",
        index.unreadable,
    )
