"""The slide editor: one record, as the slide it contributes to its cycle's deck.

A deck is generated, and a generated deck is the floor somebody edits up from
rather than the ceiling — `deck.py` has said so since it was written, and until
now there was no way to do the editing. This is that way: three panes on the
record's own page, at `/detail/<id>?view=slide`.

**On the record's page and not on a page of its own.** jcanton, 2026-08-25:
"don't make it /slide/<id> but keep it in /detail/<id> if possible". It is a
query on the same path, so the address is the record's, a link to it is a link
to the record, and the back button behaves. It is a separate RENDERER because
`detail.py` is three thousand lines of one page's machinery — a co-editing
socket, a draft store, four view states and two editors — and none of it is what
a slide editor needs. A fourth state threaded through `showView` would have
inherited all of it to use none of it.

**Three panes, not four.** The record as it reads on the left — facts above the
document, the arrangement the record page already draws — the choosing in the
middle, the slide as it will look on the right. There is no frontmatter editor
in the middle pane because a slide's frontmatter is DERIVED: the title, the
chips, the appetite, the owner and the id all come off the record, they are on
the left already, and a box to retype them into would be the second copy of one
fact this whole tool exists to end.

**One save model, and it is the record's.** Save writes `slide:` through
`PATCH /api/record/<id>`, the same door the record page uses, so a slide edit
gets the same compare-and-swap, the same three-way merge and the same conflict
report as everything else. The body editor is not on screen in this mode, so the
page still has exactly one thing Save means.
"""

from __future__ import annotations

from collections.abc import Callable

from markupsafe import Markup

from ..index import Index
from ..model import Record, lead_text
from ..vendor import _ace
from .deck import _DECK_STYLE, _deck_view, _said, _seeded, choosable, slide_html
from .detail import _body_html, _fact_rows, _progress_view
from .editor import _ACE_SURFACE, _ace_wanted
from .env import _fragment
from .markdown import _inlined_assets
from .shell import ROUTES, Links, _page
from .styles import _DETAIL_STYLE
from .tokens import _human


def _boxes(record: Record) -> list[dict]:
    """The section checkboxes, reconciled with the record as it is right now.

    **The reconciliation is here and it writes nothing.** jcanton asked for a
    "bottommatter which is autogenerated when opening the slide editing page",
    and this is that, minus the write: a GET that commits would fire on every
    visit, including every visit by somebody the write path would refuse, so
    opening the page would be a 403 for a reader and a commit for everybody
    else. Computing it on open and storing it on Save is the same outcome with
    neither.

    A section the record has grown since the slide was last saved is offered
    unticked — jcanton, 2026-08-25: "newly-discovered section should always
    arrive but not checked, default is leave out". A record that has never been
    personalised is seeded from `_seeded` instead, so its boxes describe the
    slide the deck is drawing for it today and pressing Save without touching
    anything changes nothing. Without that carve-out the first Save on every
    record in the plan would have blanked its slide.

    A name stored by a section that has since been DELETED is not offered, and
    is not lost either: it stays in the file, `only_sections` matches nothing for
    it, and it starts drawing again if the heading comes back. Dropping it here
    would turn a rename-and-rename-back into a silent deletion.
    """
    stored = record.slide if record.slide is not None else _seeded(record)
    chosen = set(stored.sections)
    fresh = record.slide is None
    return [
        {
            "name": name,
            "label": _human(name),
            "on": name in chosen,
            # What the box would have been, so the editor can mark what has
            # arrived since the last save. A person who opens a slide they
            # personalised in July wants to see WHICH heading is new, not to
            # diff two lists in their head.
            "new": not fresh and name not in chosen,
            "bet": is_bet,
        }
        for name, is_bet in choosable(record)
    ]


def _place(index: Index, record: Record) -> int | None:
    """Which slide of its cycle's deck this record's first slide is, counting the
    title slide as one.

    Asked of `_deck_view` itself rather than counted here, so the number on this
    page and the number under the presenter's thumb are the same number. A second
    count would agree with the deck until the day somebody changed the ordering
    or the leaf rule, and then it would be a page confidently naming the wrong
    slide — which is worse than naming none.
    """
    if record.cycle is None:
        return None
    drawn = _deck_view(index, record.cycle, ROUTES)["slides"]
    for at, one in enumerate(drawn):
        if one["id"] == record.id:
            # Plus two: `enumerate` is zero-based and the title slide is drawn
            # by the template rather than by `slides`, so it is in neither.
            return at + 2
    return None


_SLIDE = """
<p class="back deckbar">
  {#- Back to the deck this slide is IN, which is where somebody arrived from
      and the only place the slide means anything. A record with no cycle has no
      deck to go back to and gets the record instead — a dead link is worse than
      a different one. -#}
  {% if e.cycle and links.deck %}<a href="{{ links.deck }}{{ e.cycle }}">← deck {{ e.cycle }}</a>
  {% else %}<a href="{{ links.record }}{{ e.id }}">← {{ e.title }}</a>{% endif %}
</p>

<article class="slideedit" data-id="{{ e.id }}">
  <h1>{{ e.title }}</h1>
  {#- Whether this slide will actually be DRAWN, said before anybody spends ten
      minutes on it. `_deck_view` takes leaves only and takes them from one
      cycle, so there are two ordinary ways to be looking at a slide that no deck
      contains — and neither of them is a fault, so neither is an error. The
      editor works in both: what is refused is letting somebody find out
      afterwards. -#}
  <p class="meta"><code>{{ e.id }}</code> ·
    {% if not e.cycle %}<span class="hint">this record is not bet into a cycle,
      so it is on no deck yet — the slide is here and will be drawn the moment it
      is</span>
    {% elif e.rollup %}<span class="hint">this record's tasks each get their own
      slide, so it has none of its own — a rollup on a deck would put the same
      work on the screen twice. The slide below is what it would draw if its
      tasks went away.</span>
    {% elif e.at and links.deck %}<a href="{{ links.deck }}{{ e.cycle }}">slide {{ e.at }} of the
      cycle {{ e.cycle }} deck</a>
    {% elif links.deck %}<a href="{{ links.deck }}{{ e.cycle }}">on the cycle
      {{ e.cycle }} deck</a>
    {#- `links.deck` is empty in the static export, where a deck is of one cycle
        and the export writes one file per view of the whole plan — so there is
        no file to point at. The cycle page has the same guard for the same
        reason: no link, rather than a link to something nobody wrote. -#}
    {% else %}<span class="hint">on the cycle {{ e.cycle }} deck</span>{% endif %}</p>

  {% if editable %}
  {#- Save and Reset, in the bar the other editors put them in and with the same
      two words. Reset undoes and stays — it does not leave the editor — which is
      the decision `_editbar` records on the record page; a second spelling of
      one control is how `in_progress` became three different words. -#}
  <p class="editbar" id="editbar">
    <button type="button" id="save" class="primary">Save</button>
    <button type="button" id="reset">Reset</button>
    <span class="hint" id="state" role="status" aria-live="polite"></span>
  </p>
  <input type="hidden" id="base" value="{{ base_commit }}">
  {% endif %}

  <div class="panes3">
    {#- LEFT: the record as it reads. The same facts list and the same document
        the record page draws, from the same three functions, because a second
        rendering of a record is a second thing to keep in step — and this is
        the pane somebody is reading FROM while they decide what goes on the
        slide, so it has to be what the record actually says. -#}
    <section class="pane read" aria-label="The record">
      <dl class="facts">
        {% for row in e.rows %}
        <dt class="{% if row.derived %}derived{% endif %}">{{ row.label }}</dt>
        <dd class="{% if row.derived %}derived{% endif %}">{{ row.display }}</dd>
        {% endfor %}
      </dl>
      {#- A pitch's rollup, where there is one. `tasks` and never `items`: a
          Jinja lookup finds `dict.items` first and the template raises
          `'builtin_function_or_method' object is not iterable` — which
          `_progress_view` has a comment about, written the last time somebody
          did this, and which this template did anyway. -#}
      {% if e.progress %}
      <section class="progress">
        <h2>Progress <span class="tally">{{ e.progress.text }}</span></h2>
        <ul>{% for task in e.progress.tasks %}
          <li class="{{ 'ticked' if task.done else '' }}"><span class="chip
            {{ task.status_class }}">{{ task.status|human }}</span> {{ task.title }}</li>
          {% endfor %}</ul>
      </section>
      {% endif %}
      <div class="doc read">{{ e.body }}</div>
    </section>

    {#- CENTRE: what goes on the slide. -#}
    <section class="pane pick" aria-label="What goes on the slide">
      <p class="choice drop">
        <label><input type="checkbox" id="skip" {% if e.slide.skip %}checked{% endif %}>
          Leave this slide out of the deck</label>
        <span class="hint">It stays on the rail, greyed, so you can put it back.</span>
      </p>

      {#- The two the deck already lifted, above the line, because that is where
          they are drawn on the slide itself: the ticked points and the pull
          requests sit above the rule the document starts under. -#}
      <fieldset class="choice">
        <legend>Above the line</legend>
        <label><input type="checkbox" class="opt" data-key="progress"
          {% if e.slide.progress %}checked{% endif %}> Include progress</label>
        <label><input type="checkbox" class="opt" data-key="prs"
          {% if e.slide.prs %}checked{% endif %}> Include PRs</label>
      </fieldset>

      <fieldset class="choice">
        <legend>From the record's body</legend>
        {% if e.lead_exists %}
        <label><input type="checkbox" class="opt" data-key="lead"
          {% if e.slide.lead %}checked{% endif %}> Opening text</label>
        {% endif %}
        {% for box in e.boxes %}
        <label class="{% if box.new %}fresh{% endif %}">
          <input type="checkbox" class="sec" value="{{ box.name }}"
            {% if box.on %}checked{% endif %}> {{ box.label }}
          {% if box.bet %}<span class="tag">the bet</span>{% endif %}
          {% if box.new %}<span class="tag new">new</span>{% endif %}
        </label>
        {% endfor %}
        {% if not e.boxes and not e.lead_exists %}
        <p class="hint">This record's document has nothing in it yet. Whatever you
           write below is the whole slide.</p>
        {% endif %}
      </fieldset>

      <p class="field">
        <label for="prose">And on the slide, in your own words</label>
        <textarea id="prose" name="prose" class="field"
          rows="12">{{ e.slide.body }}</textarea>
        <span class="hint">Markdown. A line reading <code>\\newslide</code> starts
          another slide for this record — the second is titled
          “{{ e.title }} (2)”. Paste or drop a picture to put it in the plan.</span>
      </p>
    </section>

    {#- RIGHT: the slide, built by the same function the deck builds it with, so
        this pane and the projector cannot disagree. -#}
    <section class="pane show" aria-label="The slide">
      <div class="sized" id="preview">{{ e.preview }}</div>
      <p class="hint" id="fitnote" role="status" aria-live="polite"></p>
    </section>
  </div>
</article>
"""


_SLIDE_STYLE = """
/* Three columns that each scroll on their own, because they are three different
   documents about one thing and a reader moves down one of them at a time. The
   middle is the widest because it is the only one being typed into; the right is
   sized to the slide's own 16:9 rather than to a share of the row, so the
   preview is never a shape the projector is not. */
.panes3 {
  display: grid; grid-template-columns: 1fr 1.15fr 1fr; gap: 1rem;
  align-items: start;
}
.panes3 .pane {
  min-width: 0; max-height: calc(100vh - 12rem); overflow: auto;
  border: 1px solid var(--line); border-radius: 4px; padding: .9rem 1rem;
  background: var(--surface);
}
/* One column under a narrow window, in reading order: what the record says,
   then what you are choosing, then what it looks like. `1100px` is where the
   middle column stops holding a checkbox label and its two tags on one line. */
@media (max-width: 1100px) { .panes3 { grid-template-columns: 1fr; } }

.panes3 .facts { margin: 0 0 1rem; }
.panes3 .read .doc { border-top: 1px solid var(--line); padding-top: .8rem; }

.choice { border: 0; margin: 0 0 1rem; padding: 0; }
.choice legend {
  font-size: 11px; font-weight: 600; letter-spacing: .06em;
  text-transform: uppercase; color: var(--muted); padding: 0;
}
.choice label { display: flex; align-items: baseline; gap: .45rem; margin: .3rem 0; }
/* The one control on this page that takes something away, so it is separated
   from the ones that add. */
.choice.drop { border-bottom: 1px solid var(--line); padding-bottom: .8rem; }
.choice .tag {
  font-size: 10px; letter-spacing: .04em; text-transform: uppercase;
  color: var(--muted); border: 1px solid var(--line); border-radius: 3px;
  padding: 0 .3rem;
}
/* What has arrived since this slide was last saved. Marked rather than ticked:
   the rule is that a new section stays out until somebody says otherwise, and a
   mark is how they find out there is something to say. */
.choice .tag.new { color: var(--warn); border-color: var(--warn); }

/* The preview is the deck's own slide at the width of this column. `.sized` is
   the deck stylesheet's fixed-canvas switch, so this pane gets the same 1280x720
   geometry, the same clip and the same `.spills` mark as the projector — which
   is the entire point of the pane. */
#preview { --fit: .32; }
#preview .slide { margin: 0 auto; }
"""


_SLIDE_SCRIPT = """
<script>
(() => {
const ID = {{ e.id|tojson }};
const MAY_WRITE = {{ editable|tojson }};
const ARTICLE = document.querySelector('.slideedit');
const PROSE = document.getElementById('prose');
const PREVIEW = document.getElementById('preview');
const FITNOTE = document.getElementById('fitnote');
const SAVE = document.getElementById('save');
const RESET = document.getElementById('reset');
const STATE = document.getElementById('state');
const BASE = document.getElementById('base');
// The document as it was when this page was rendered, and the ONE thing Reset
// restores from. Never `defaultValue`: a browser restoring a form on a back
// navigation writes the box and leaves `defaultValue` alone, so Reset would
// have put back something the reader never saw. Same decision, same reason, as
// the record editor's `BASELINE`.
const BASELINE = JSON.stringify(state());
// Ace, where the page was given it. The plain box stays in the DOM and stays
// the thing `state()` reads, exactly as it does on the record page — one place
// knows a textarea has a `.value`, and it is not this file.
const SURFACE = window.aceSurface && MAY_WRITE ? aceSurface(PROSE, PROSE.value) : null;
const text = () => SURFACE ? SURFACE.text() : PROSE.value;

function state() {
  const on = key => {
    const box = ARTICLE.querySelector(`.opt[data-key="${key}"]`);
    return box ? box.checked : true;
  };
  return {
    skip: document.getElementById('skip').checked,
    progress: on('progress'),
    prs: on('prs'),
    lead: on('lead'),
    sections: [...ARTICLE.querySelectorAll('.sec')]
      .filter(box => box.checked).map(box => box.value),
    body: typeof text === 'function' ? text() : PROSE.value,
  };
}

function dirty() { return JSON.stringify(state()) !== BASELINE; }

function said(words) { if (STATE) STATE.textContent = words; }

// --- The preview --------------------------------------------------------
// Asked of the SERVER, and that is the decision worth the round trip. A slide
// is markdown through `_markdown`, sections chosen by `only_sections`, a
// checklist lifted by `checklist_items` and pull requests linked by `_pr_link` —
// five functions in Python, none of which exists in this page. A preview drawn
// here would be a sixth rendering of a slide, written in a second language,
// agreeing with the projector only for as long as somebody kept it in step. The
// deck's whole argument is against exactly that.
let asked = null;
let waiting = false;
const PREVIEW_MS = 400;

async function draw() {
  waiting = false;
  const sending = JSON.stringify(state());
  const answer = await fetch('/api/slide/preview', {
    method: 'POST',
    headers: {'content-type': 'application/json'},
    body: JSON.stringify({record_id: ID, slide: state()}),
  });
  if (!answer.ok) {
    // The preview failing is not the save failing, and it must not read as
    // though it were: the text in the box is untouched and still saveable.
    FITNOTE.textContent = 'The preview could not be drawn just now.';
    return;
  }
  const drawn = await answer.json();
  PREVIEW.innerHTML = drawn.html;
  fit();
}

function refresh() {
  if (waiting) clearTimeout(asked);
  waiting = true;
  asked = setTimeout(draw, PREVIEW_MS);
}

// Does it fit? Asked of the browser, after the drawing, because whether 300
// words fit in 720px depends on the font and the wrapping and only the thing
// doing the layout knows both. This is the pane's real job: the canvas is fixed
// and clipped, so without this mark an author would be told nothing at all
// about the paragraph the room is never going to see.
function fit() {
  const room = PREVIEW.clientWidth;
  if (room > 0) PREVIEW.style.setProperty('--fit', String(room / 1280));
  const over = [...PREVIEW.querySelectorAll('.slide')]
    .filter(slide => slide.scrollHeight > slide.clientHeight + 1);
  for (const slide of PREVIEW.querySelectorAll('.slide'))
    slide.classList.toggle('spills', over.includes(slide));
  FITNOTE.textContent = over.length
    ? `${over.length} of these slides ${over.length === 1 ? 'holds' : 'hold'} more than fits. `
      + 'Take something out, or split it with \\\\newslide.'
    : '';
}

// --- Saving -------------------------------------------------------------
async function save() {
  if (!MAY_WRITE) return;
  SAVE.disabled = true;
  said('Saving…');
  try {
    const answer = await fetch('/api/record/' + encodeURIComponent(ID), {
      method: 'PATCH',
      headers: {'content-type': 'application/json'},
      // `body: null` and not the record's body: this editor does not have the
      // record's document on screen and must not write one. A save that carried
      // an empty body would erase the shaping document from a page that never
      // showed it.
      body: JSON.stringify({base_commit: BASE.value, fields: {slide: state()}, body: null}),
    });
    const result = await answer.json().catch(() => ({}));
    if (!answer.ok) {
      // The message the server wrote, because it names the field and why. A
      // generic "could not save" here would throw away the one sentence that
      // says what to do about it.
      said(result.detail || 'That could not be saved.');
      return;
    }
    if (result.commit) BASE.value = result.commit;
    said('Saved.');
  } finally {
    SAVE.disabled = false;
  }
}

if (MAY_WRITE) {
  SAVE.addEventListener('click', save);
  RESET.addEventListener('click', () => {
    const was = JSON.parse(BASELINE);
    document.getElementById('skip').checked = was.skip;
    for (const box of ARTICLE.querySelectorAll('.opt'))
      box.checked = was[box.dataset.key];
    for (const box of ARTICLE.querySelectorAll('.sec'))
      box.checked = was.sections.includes(box.value);
    // `splice` and never `setValue`: it is the surface's only write, and
    // `test_the_second_surface_never_sets_or_replaces_the_whole_document` holds
    // it to that by reading the shipped page. Whole-document boundaries, so the
    // UTF-16 index space `positionToIndex` uses cannot cut a surrogate pair —
    // the defect that shipped once already and rewrote somebody's emoji.
    if (SURFACE) SURFACE.splice(0, text().length, was.body);
    else PROSE.value = was.body;
    said('Reset.');
    refresh();
  });
  // Nothing autosaves here, so leaving with unsaved work has to be said. One
  // model per page and it is visible: the bar carries the state and this is the
  // last thing it can say.
  addEventListener('beforeunload', event => {
    if (dirty()) event.preventDefault();
  });
}

ARTICLE.addEventListener('change', refresh);
if (SURFACE) SURFACE.onInput(refresh); else PROSE.addEventListener('input', refresh);
addEventListener('resize', fit);
document.fonts?.ready.then(fit);
fit();
})();
</script>
"""


def render_slide_editor(
    index: Index,
    record_id: str,
    links: Links = ROUTES,
    base_commit: str | None = None,
    may_write: bool = False,
    editor: str = "ace",
    asset: Callable[[str], bytes | None] | None = None,
) -> str:
    """One record's slide, as three panes on the record's own address.

    `base_commit` and `may_write` decide whether this is an editor or a reading
    of one, the same way they do on the record page and for the same reason: a
    reader offered a Save is offered a 403 dressed as a control, and the three
    panes are worth reading either way — the middle one simply becomes the list
    of what this slide is made of.
    """
    record = index.records[record_id]
    editable = bool(base_commit and may_write)
    slide = record.slide if record.slide is not None else _seeded(record)
    assets = _inlined_assets([record.body, slide.body], asset) if asset else {}
    view = {
        "id": record.id,
        "title": record.title,
        "cycle": record.cycle,
        # A pitch with tasks under it is a rollup and `_deck_view` gives it no
        # slide — its progress IS its tasks and its people are their people, so
        # a slide of its own would put the same work on the screen twice. Read
        # from the index rather than restated, so this and the deck cannot come
        # to different conclusions about what a leaf is.
        "rollup": bool(index.children.get(record.id)),
        # Which slide of the deck this is, so the line above is a place and not
        # only a link. `None` where the record is on no deck at all, which the
        # branch above has already taken.
        "at": _place(index, record),
        "rows": _fact_rows(index, record, links),
        "progress": _progress_view(index, record),
        "body": _body_html(record, links),
        "slide": slide,
        "boxes": _boxes(record),
        # Whether there is any opening text to offer a box for. A checkbox
        # governing something the record does not have is a control whose only
        # honest state is off, and a row of those is how a form stops being read.
        "lead_exists": bool(lead_text(_said(record))),
        "preview": slide_html(index, record, links, assets),
    }
    # `_fragment` and not `_compiled(...).render(...)`, which is what this was
    # and which silently escaped the whole page. `render` answers a `str`, so
    # `str + Markup` reaches `Markup.__radd__`, which escapes the left side: the
    # body arrived at `_page` as `&lt;article class=&#34;slideedit&#34;…`, a
    # complete and completely inert copy of the editor. `_fragment` types the
    # piece as the markup it is, which is the whole reason it exists — its own
    # docstring says so.
    ace = _ace_wanted(editor, base_commit, may_write)
    return _page(
        f"openproj — {record.title}: the slide",
        _fragment(
            _SLIDE + _SLIDE_SCRIPT,
            e=view,
            links=links,
            editable=editable,
            base_commit=base_commit or "",
        )
        + (_ace() if ace else Markup(""))
        + (_ACE_SURFACE if ace else Markup("")),
        _DETAIL_STYLE + _DECK_STYLE + _SLIDE_STYLE,
        links,
        "records",
        index.unreadable,
    )
